id: IBB3571A3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:12:10+00:00'
last_modified: '2022-06-08T03:11:13.185714+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11708
  title: དྲང་སྲོང་གཟའ་རྒོད་ཀྱི་སྒྲུབ་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E8BF:
      image_group_id: I1KG11717
      title: ''
      total_pages: 645
      order: 1
      base_file: E8BF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
