id: P005452
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG11708
  title: དྲང་སྲོང་གཟའ་རྒོད་ཀྱི་སྒྲུབ་སྐོར།
  author: ''
  volumes:
    98a04bedfe2d4a7b8dc619599ac44fb5:
      image_group_id: I1KG11717
      title: ''
      volume_number: 1
      total_pages: 645
      base_file: v001.txt
